spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/wisdom?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true

server:
  port: 9090

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    root: info
    cn.jit.wisdom: debug
